# utils/quarto_renderer.py
import subprocess
import tempfile
from pathlib import Path
from typing import Optional, List

class QuartoRenderer:
    """Quarto 문서 생성 및 렌더링"""
    
    def __init__(self):
        self.temp_dir = Path(tempfile.mkdtemp())
        
    def create_qmd_document(
        self, 
        title: str,
        author: str,
        experiment_date: str,
        code_chunks: List[dict],
        theme: str = "cosmo",
        code_fold: bool = True,
        output_path: Optional[str] = None
    ) -> Path:
        """Quarto 문서 생성"""
        
        yaml_header = f"""---
title: "{title}"
subtitle: "Google Gemini를 활용한 자동 분석 리포트"
author: "{author}"
date: "{experiment_date}"
format:
  html:
    code-fold: {"true" if code_fold else "false"}
    code-tools: true
    code-copy: true
    toc: true
    toc-depth: 3
    toc-location: left
    theme: {theme}
    smooth-scroll: true
    highlight-style: github
    number-sections: true
    fig-cap-location: bottom
  pdf:
    documentclass: article
    geometry: 
      - margin=1in
    toc: true
    number-sections: true
    colorlinks: true
jupyter: python3
execute:
  warning: false
  message: false
---

"""
        
        abstract = f"""
## 실험 개요 {{.unnumbered}}

- **실험 제목**: {title}
- **실험자**: {author}
- **실험 날짜**: {experiment_date}
- **분석 도구**: Bio-Log v2.0 (Google Gemini 2.0)
- **총 분석 수**: {len(code_chunks)}개

---

"""
        
        content = yaml_header + abstract
        
        for i, chunk in enumerate(code_chunks, 1):
            lang = chunk.get('language', 'python')
            code = chunk.get('code', '')
            caption = chunk.get('caption', f'분석 {i}')
            interpretation = chunk.get('interpretation', '')
            
            content += f"""
## 분석 {i}: {caption}

"""
            
            content += f"""```{{{lang}}}
#| label: fig-analysis-{i}
#| fig-cap: "{caption}"

{code}
```

"""
            
            if interpretation:
                content += f"""
### 결과 해석

{interpretation}

"""
            
            content += "\n---\n\n"
        
        content += """
## 결론 및 제언 {.unnumbered}

본 분석은 Google Gemini AI를 활용하여 자동 생성되었습니다. 
통계적 결과는 실험 설계와 데이터 품질에 따라 달라질 수 있으므로, 
항상 도메인 전문가의 검토가 필요합니다.

---

*Generated by Bio-Log - AI-Powered Lab Notebook*
"""
        
        if output_path is None:
            output_path = self.temp_dir / "report.qmd"
        else:
            output_path = Path(output_path)
        
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding='utf-8')
        
        return output_path
    
    def render_to_html(self, qmd_path: Path) -> Path:
        """Quarto 문서를 HTML로 렌더링"""
        
        try:
            result = subprocess.run(
                ['quarto', 'render', str(qmd_path), '--to', 'html'],
                capture_output=True,
                text=True,
                check=True,
                timeout=60,
                cwd=str(qmd_path.parent),
                encoding='utf-8',
                errors='replace'
            )
            
            html_path = qmd_path.with_suffix('.html')
            
            if not html_path.exists():
                raise FileNotFoundError(f"렌더링 완료되었으나 파일을 찾을 수 없음: {html_path}")
            
            return html_path
            
        except subprocess.TimeoutExpired:
            raise RuntimeError("렌더링 시간 초과 (60초)")
        except subprocess.CalledProcessError as e:
            error_msg = f"Quarto 렌더링 실패 (exit code {e.returncode}):\n"
            if e.stdout:
                error_msg += f"--- STDOUT ---\n{e.stdout}\n"
            if e.stderr:
                error_msg += f"--- STDERR ---\n{e.stderr}\n"
            raise RuntimeError(error_msg)
        except FileNotFoundError:
            raise RuntimeError("Quarto가 설치되어 있지 않습니다. https://quarto.org 에서 설치하세요.")
    
    def render_to_pdf(self, qmd_path: Path) -> Path:
        """Quarto 문서를 PDF로 렌더링"""
        
        try:
            result = subprocess.run(
                ['quarto', 'render', str(qmd_path), '--to', 'pdf'],
                capture_output=True,
                text=True,
                check=True,
                timeout=120,
                cwd=str(qmd_path.parent),
                encoding='utf-8',
                errors='replace'
            )
            
            pdf_path = qmd_path.with_suffix('.pdf')
            
            if not pdf_path.exists():
                raise FileNotFoundError(f"PDF 생성 실패: {pdf_path}")
            
            return pdf_path
            
        except subprocess.CalledProcessError as e:
            if "pdflatex" in e.stderr or "xelatex" in e.stderr:
                raise RuntimeError(
                    "PDF 생성에 필요한 LaTeX가 설치되어 있지 않습니다.\n"
                    "TinyTeX 설치: quarto install tinytex"
                )
            else:
                error_msg = f"PDF 렌더링 실패 (exit code {e.returncode}):\n"
                if e.stdout:
                    error_msg += f"--- STDOUT ---\n{e.stdout}\n"
                if e.stderr:
                    error_msg += f"--- STDERR ---\n{e.stderr}\n"
                raise RuntimeError(error_msg)
